### ISSUE TITLE
allow user to use e.g. bulk_value computation without building a complete TEF object first

### ISSUE THREAD

**Issue by florianboergel** [florianboergel/pyTEF#31]
In contrast is should be also possible to do that!

**Comment by MarvinLorenz** [comment]
Würde auch alle wichtigen Funktionen so zugänglich machen, also vor allem binning (und convert_q_to_Q). Dann kann jede:r diese Funktionen nutzen, in andere Skripte einbauen, wie er/sie möche. Also output = pyTEF.sort_1dim(...), bulk_output = pyTEF.calc_bulk_values(s_Q,Q).
Das würde ja vor allem Leute inkludieren, die vielleicht mit Beobachtungen arbeiten und keine großen netCDF files haben. Wobei man natürlich auch txt files, excel Tabellen etc mit xarray einlesen kann. Wäre vielleicht auch ein Beispiel Wert, wobei die Anwendung ja identisch zur bisherigen wäre, also vielleicht doch eher nicht.
