### ISSUE TITLE
.get_depth_name() etc

### ISSUE THREAD

**Issue by MarvinLorenz** [florianboergel/pyTEF#40]
In sort_1dim etc we have:
out_q[:, i] = transport.where(idx == i).sum([self._get_name_depth(),
                                                     self._get_name_latitude(),
                                                     self._get_name_longitude()],dtype=np.float64) / delta_var

which will not work if the dimension names are not in the lists we have in the repsective _get_dimension_name function. E.g. I have a dataset, where I used
tef.set_up(depth_name='z')

when using the sorting function, I get an error than summation over None is not possible, since self._get_depth_name() returns None

using self._depth_name did not work since tef.ds does not have the respective attribute declared.

**Comment by florianboergel** [comment]
You are right. I thout one way to avoid this is that instead of calling `._get_name_depth()` you could call `self._depth_name`, since this variable is always assigned using `.set_up`. Why is this not working? I will also check after I am back at my computer.

**Comment by MarvinLorenz** [comment]
I dont know why ._depth_name() did not work for me. Could be that the attribute is not passed to tef.ds ...

Maybe the better solution is to change ._get_depth_name() to check if ._name_depth is not None as well and then return ._name_depth. In principle set_up() sets all the names up, but ._get_depth_name() still returns None if its name is not in the list of ['level','depth'] ... I think the latter solution is cleaner. What do you think?

**Comment by florianboergel** [comment]
Should be solved with #42
