### ISSUE TITLE
.data bug in calc

### ISSUE THREAD

**Issue by MarvinLorenz** [florianboergel/pyTEF#43]
Dear Marvin,

I recently tried to use your pytef package for TEF analysis and found a bug. my xarray version is 0.21.1 and when I run example2, I get an error in calc.py at line 162, the error is: TypeError: Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.
This may be caused by the different xarray version, and can be solved by using the .data property at the corresponding code.

Cheers, yang

**Comment by florianboergel** [comment]
Should be resolved with 90bd898814151f8717a59d724eee6f4806003ce2
